{{- range $color, $config := dict "blue" .Values.blue "green" .Values.green }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-{{ $color }}
  labels:
    app: {{ $color }}-webserver
    version: {{ $color }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app: webserver
      ver: {{ $color }}
  template:
    metadata:
      labels:
        app: webserver
        ver: {{ $color }}
    spec:
      securityContext:
        runAsUser: {{ $config.securityContext.runAsUser }}
        runAsGroup: {{ $config.securityContext.runAsGroup }}
        fsGroup: {{ $config.securityContext.fsGroup }}
      containers:
        - name: webserver-container
          image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: NGINX_PORT
              value: "8080"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            {{- range $config.extraVolumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
            - name: run-log
              mountPath: /var/run
            - name: run-log
              mountPath: /var/log/nginx
      volumes:
        {{- range $config.volumes }}
        - name: {{ .name }}
          emptyDir: {}
        {{- end }}
        - name: run-log
          emptyDir: {}
{{- end }}
