apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-{{ .Values.color }}
  labels:
    app: {{ .Values.color }}-webserver
spec:
  replicas: {{ index .Values .Values.color "replicaCount" }}
  selector:
    matchLabels:
      app: webserver
      ver: {{ .Values.color }}
  template:
    metadata:
      labels:
        app: webserver
        ver: {{ .Values.color }}
    spec:
      containers:
        - name: webserver-container
          image: "{{ index .Values .Values.color "image" "repository" }}:{{ index .Values .Values.color "image" "tag" }}"

