apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  labels:
    app: blue-green-webserver
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  selector:
    app: webserver
    ver: {{ .Values.serviceSelectorColor }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}

