containerPort: 8080

serviceSelectorColor: green

service:
  type: NodePort
  port: 80
  nodePort: 30010

blue:
  replicaCount: 4
  image:
    repository: eyesoncloud/web-app
    tag: v1
  volumes:
    - name: tmp-volume
      emptyDir: {}

green:
  replicaCount: 3
  image:
    repository: eyesoncloud/web-app
    tag: v2
  volumes:
    - name: tmp-volume
      emptyDir: {}

