serviceSelectorColor: blue

service:
  type: NodePort
  port: 80
  nodePort: 30010

blue:
  replicaCount: 4
  image:
    repository: eyesoncloud/web-app
    tag: v1
  securityContext:
    runAsUser: 1000680001
    fsGroup: 1000680001
  extraVolumeMounts:
    - name: nginx-temp
      mountPath: /var/cache/nginx
  volumes:
    - name: nginx-temp
      emptyDir: {}

green:
  replicaCount: 3
  image:
    repository: eyesoncloud/web-app
    tag: v2
  securityContext:
    runAsUser: 1000680001
    fsGroup: 1000680001
  extraVolumeMounts:
    - name: nginx-temp
      mountPath: /var/cache/nginx
  volumes:
    - name: nginx-temp
      emptyDir: {}
