blue:
  replicaCount: 4
  image:
    repository: eyesoncloud/web-app
    tag: v1
  ingress:
    enabled: false
  securityContext:
    runAsUser: 1001
    fsGroup: 1001
  extraVolumeMounts:
    - name: nginx-temp
      mountPath: /var/cache/nginx
  volumes:
    - name: nginx-temp
      emptyDir: {}

green:
  replicaCount: 3
  image:
    repository: eyesoncloud/web-app
    tag: v2
  ingress:
    enabled: false
  securityContext:
    runAsUser: 1001
    fsGroup: 1001
  extraVolumeMounts:
    - name: nginx-temp
      mountPath: /var/cache/nginx
  volumes:
    - name: nginx-temp
      emptyDir: {}

serviceSelectorColor: blue
service:
  type: NodePort
  nodePort: 30010
  port: 80
